name: Application Tracker Docker Image CI

on:
  push:
    branches:
      - "develop"
      - "main"
      - "release-*"
  pull_request:
    branches:
      - "develop"
      - "main"
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: docker build . --file Dockerfile --tag michaelhauser/application-tracker:${{ github.ref_name }}-$(date +%s)
